"""Export all push narratives into a single DEV_STORY.md document."""
from pathlib import Path

narr_dir = Path('docs/push_narratives')
files = sorted(narr_dir.glob('*.md'))

first_date = files[0].stem.rsplit('_', 1)[0]
last_date = files[-1].stem.rsplit('_', 1)[0]

parts = [
    '# Keystroke Telemetry — Full Dev Story',
    '',
    f'> {len(files)} push narratives from {first_date} to {last_date}',
    '> Each section = one git push. Auto-generated by the pigeon compiler post-commit hook.',
    '> Copy this entire document into any LLM for full project context.',
    '',
    '---',
    '',
]

for f in files:
    content = f.read_text('utf-8', errors='ignore').strip()
    date, commit = f.stem.rsplit('_', 1)
    parts.append(f'## Push: {date} — `{commit}`')
    parts.append('')
    lines = content.splitlines()
    start = 0
    if lines and lines[0].startswith('# '):
        start = 1
    parts.append('\n'.join(lines[start:]).strip())
    parts.append('')
    parts.append('---')
    parts.append('')

out = Path('docs/DEV_STORY.md')
out.write_text('\n'.join(parts), 'utf-8')
total_chars = len('\n'.join(parts))
print(f'Written: {out} ({total_chars:,} chars, {len(files)} narratives)')
