import json
from pathlib import Path
root = Path('.')
reg = json.loads((root/'pigeon_registry.json').read_text(encoding='utf-8'))
print(f'Registry modules: {len(reg)}')
journal = (root/'logs'/'prompt_journal.jsonl').read_text(encoding='utf-8').strip().splitlines()
print(f'Journal entries: {len(journal)}')
comps = (root/'logs'/'prompt_compositions.jsonl').read_text(encoding='utf-8').strip().splitlines()
dw_count = sum(1 for l in comps if json.loads(l).get('deleted_words'))
print(f'Compositions: {len(comps)}, with deleted: {dw_count}')
nm = json.loads((root/'pigeon_brain'/'node_memory.json').read_text(encoding='utf-8'))
total_e = sum(len(v) for v in nm.values())
print(f'Node memory: {len(nm)} nodes, {total_e} entries')
scores = json.loads((root/'pigeon_brain'/'prediction_scores.json').read_text(encoding='utf-8'))
print(f'Predictions scored: {len(scores)}')
cal = json.loads((root/'pigeon_brain'/'prediction_calibration.json').read_text(encoding='utf-8'))
print(f'Calibration: conf={cal.get("avg_confidence",0):.3f} actual={cal.get("avg_actual",0):.3f}')
narrs = list((root/'docs'/'push_narratives').glob('*.md'))
print(f'Push narratives: {len(narrs)}')
state = json.loads((root/'pigeon_brain'/'learning_loop_state.json').read_text(encoding='utf-8'))
print(f'Loop: cycles={state["total_cycles"]} fwd={state["total_forward"]} bwd={state["total_backward"]} pred={state.get("total_predictions",0)}')
sub = list((root/'pigeon_brain'/'flow').rglob('*.py'))
print(f'Flow engine total files: {len(sub)}')
selffix = list((root/'docs'/'self_fix').glob('*.md'))
print(f'Self-fix reports: {len(selffix)}')
hm = json.loads((root/'file_heat_map.json').read_text(encoding='utf-8'))
print(f'Heat map modules: {len(hm)}')
# copilot instructions mutation count
ci = (root/'.github'/'copilot-instructions.md').read_text(encoding='utf-8')
mut_line = [l for l in ci.splitlines() if 'mutated' in l.lower()]
if mut_line: print(f'Prompt mutations: {mut_line[0].strip()}')
print(f'Copilot instructions lines: {len(ci.splitlines())}')
