import json
lines = open('logs/chat_compositions.jsonl','r',encoding='utf-8').read().strip().splitlines()
e = json.loads(lines[-1])
print("keys:", list(e.keys()))
print("final_text:", repr(e.get('final_text','')[:60]))
print("signals:", e.get('signals',{}))
print("del_ratio:", e.get('deletion_ratio',0))
print("deleted_words:", e.get('deleted_words',[]))
print("chat_state:", e.get('chat_state',{}))
print("ts:", e.get('ts','?'))
print("total entries:", len(lines))
print("rewrite_chains:", e.get('rewrite_chains',[]))
print("cognitive_state:", e.get('cognitive_state','?'))
print("session_n:", e.get('session_n','?'))
