"""Maximum compression stress test.

Strips auto-regenerated bloat from all source .py files:
- Pigeon header blocks (re-injected on commit)
- Pulse blocks (re-injected on save)
- Duplicate blank line runs (>2 → 2)
- @pigeon: metadata lines (re-generated)

Does NOT strip: docstrings, comments, actual code.
Safe because all stripped content is auto-regenerated by pigeon compiler + vscode extension.
"""
import pathlib
import re
import sys

ROOT = pathlib.Path('.')
DIRS = ['src', 'pigeon_compiler', 'pigeon_brain', 'streaming_layer', 'client']
DRY_RUN = '--dry-run' in sys.argv

# patterns for auto-regenerated blocks
PIGEON_HEADER = re.compile(
    r'^# ── pigeon[^\n]*\n(?:#[^\n]*\n)*# ──+\n',
    re.MULTILINE
)
PULSE_BLOCK = re.compile(
    r'^# ── telemetry:pulse ──\n(?:#[^\n]*\n)*# ── /pulse ──\n',
    re.MULTILINE
)
PIGEON_META = re.compile(r'^# @pigeon:.*\n', re.MULTILINE)
BLANK_RUNS = re.compile(r'\n{4,}')  # 3+ blank lines → 2


def strip_file(path):
    """Strip auto-generated bloat. Returns (original_lines, new_lines, bytes_saved)."""
    try:
        txt = path.read_text('utf-8')
    except Exception:
        return 0, 0, 0

    orig_lines = len(txt.splitlines())
    orig_bytes = len(txt)

    new = txt
    new = PIGEON_HEADER.sub('', new)
    new = PULSE_BLOCK.sub('', new)
    new = PIGEON_META.sub('', new)
    new = BLANK_RUNS.sub('\n\n\n', new)

    # strip leading blank lines after header removal
    new = new.lstrip('\n')

    new_lines = len(new.splitlines())
    saved = orig_bytes - len(new)

    if saved > 0 and not DRY_RUN:
        path.write_text(new, encoding='utf-8')

    return orig_lines, new_lines, saved


def main():
    files = []
    for d in DIRS:
        p = ROOT / d
        if p.exists():
            files.extend(sorted(p.rglob('*.py')))

    total_saved = 0
    total_lines_saved = 0
    files_changed = 0
    over_cap_before = 0
    over_cap_after = 0
    biggest_wins = []

    for f in files:
        orig, new, saved = strip_file(f)
        if saved > 0:
            files_changed += 1
            total_saved += saved
            total_lines_saved += (orig - new)
            biggest_wins.append((orig - new, orig, new, str(f)))
        if orig > 200:
            over_cap_before += 1
        if new > 200:
            over_cap_after += 1

    mode = "DRY RUN" if DRY_RUN else "APPLIED"
    print(f"\n{'='*60}")
    print(f"  COMPRESSION STRESS TEST [{mode}]")
    print(f"{'='*60}")
    print(f"  Files scanned:    {len(files)}")
    print(f"  Files changed:    {files_changed}")
    print(f"  Bytes saved:      {total_saved:,}")
    print(f"  Lines saved:      {total_lines_saved:,}")
    print(f"  Over-cap before:  {over_cap_before}")
    print(f"  Over-cap after:   {over_cap_after}")
    print(f"  Cap violations fixed: {over_cap_before - over_cap_after}")
    print()

    if biggest_wins:
        biggest_wins.sort(reverse=True)
        print("  Top 20 biggest line reductions:")
        for delta, orig, new, path in biggest_wins[:20]:
            status = "✓" if new <= 200 else "!"
            print(f"    {status} -{delta:4d} lines  ({orig:4d} → {new:4d})  {path}")

    print()
    still_over = [(new, path) for delta, orig, new, path in biggest_wins if new > 200]
    changed_paths = {path for _, _, _, path in biggest_wins}
    still_over += [
        (orig, str(f))
        for f in files
        if (orig := len(f.read_text('utf-8').splitlines())) > 200
        and str(f) not in changed_paths
    ]

    if not DRY_RUN:
        print(f"  [{files_changed} files compressed on disk]")


if __name__ == '__main__':
    main()
