"""tc_profile/ — Pigeon-compliant module."""
from .tc_profile_bootstrap_decomposed_seq033_v001 import bootstrap_profile
from .tc_profile_bootstrap_finalize_seq036_v001 import bootstrap_profile
from .tc_profile_constants_seq001_v001 import PROFILE_PATH, _INTENT_STOPWORDS, _SECTION_SIGNALS
from .tc_profile_format_intelligence_decomposed_seq025_v001 import format_intelligence_for_prompt
from .tc_profile_format_profile_decomposed_seq037_v001 import format_profile_for_prompt
from .tc_profile_generate_journal_seq043_v001 import generate_profile_from_journal
from .tc_profile_generate_session_decomposed_seq042_v001 import generate_profile_from_session
from .tc_profile_generate_session_seq041_v001 import generate_profile_from_session
from .tc_profile_intent_extractors_seq039_v001 import extract_session_files, extract_session_triggers
from .tc_profile_intent_generation_seq038_v001 import detect_session_template, extract_session_files, extract_session_triggers
from .tc_profile_intent_template_seq040_v001 import detect_session_template
from .tc_profile_load_save_seq030_v001 import load_profile, save_profile
from .tc_profile_section_classify_seq006_v001 import classify_section
from .tc_profile_update_completion_decomposed_seq031_v001 import update_profile_from_completion
from .tc_profile_update_composition_decomposed_seq032_v001 import update_profile_from_composition
from .tc_profile_update_section_decomposed_seq007_v001 import update_section
