"""u_pj_s019_v002_d0402_λC/ — Pigeon-compliant module."""
from .u_pj_s019_v002_d0402_λC_constants_seq001_v001 import COMPS_PATH, COPILOT_PATH, EDIT_PAIRS, HEAT_PATH, INTENT_MAP, JOURNAL_PATH, MAX_COMP_AGE_MS, MIN_TEXT_MATCH_SCORE, MUTATIONS_PATH, PROFILE_PATH, PROMPT_BLOCK_END, PROMPT_BLOCK_START, PROMPT_COMPS_PATH, SNAPSHOT_PATH, TASK_PATH, TIGHT_WINDOW_MS
from .u_pj_s019_v002_d0402_λC_enriched_entry_decomposed_seq016_v001 import log_enriched_entry
