"""manifest_builder_seq007_build_manifest_decomposed_seq030_v001.py — Auto-extracted by Pigeon Compiler."""
from datetime import datetime, timezone
from pathlib import Path
import re

def build_manifest(folder: Path, root: Path = None) -> str:
    """Generate self-documenting MANIFEST.md content for a single folder.

    Each manifest includes a format legend, a file table with exports and
    dependencies, the folder's public API, an internal dependency graph,
    and a health summary.  Existing NOTES are preserved across rebuilds.
    """
    folder = Path(folder)
    root = Path(root) if root else folder.parent
    existing_notes = _parse_existing_notes(folder / 'MANIFEST.md')
    file_records = _scan_folder_rich(folder)
    if not file_records:
        return ''
    folder_rel = str(folder.relative_to(root)).replace('\\', '/')
    purpose = _infer_folder_purpose(folder)
    now = datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')
    lines = []

    # ── Header ────────────────────────────────
    lines.append(f'# MANIFEST — {folder_rel}')
    lines.append('')
    if purpose:
        lines.append(f'> {purpose}')
        lines.append('')
    lines.append(f'*Auto-generated by pigeon_compiler manifest_builder | {now}*')
    lines.append('')

    # ── Self-documenting legend ───────────────
    lines.append(_LEGEND.format(max=MAX_COMPLIANT))
    lines.append('')

    # ── File table ────────────────────────────
    lines.append('## Files')
    lines.append('')
    lines.append('| Seq | File | Lines | Status | Exports | Deps | Description | Notes |')
    lines.append('|-----|------|------:|--------|---------|------|-------------|-------|')
    for rec in file_records:
        status = _status_icon(rec['lines'])
        seq = rec['seq']
        note = existing_notes.get(rec['name'], '')
        exports_str = ', '.join(rec['exports'][:5])
        if len(rec['exports']) > 5:
            exports_str += f' +{len(rec["exports"]) - 5}'
        deps_str = ', '.join(rec['deps'][:4])
        if len(rec['deps']) > 4:
            deps_str += f' +{len(rec["deps"]) - 4}'
        lines.append(
            f'| {seq} | {rec["name"]} | {rec["lines"]} | {status} '
            f'| {exports_str} | {deps_str} | {rec["desc"]} | {note} |'
        )
    lines.append('')

    # ── Folder API (from __init__.py) ─────────
    api_lines = _build_folder_api(folder)
    if api_lines:
        lines.append('## Folder API')
        lines.append('')
        lines.append('Public symbols re-exported by `__init__.py`:')
        lines.append('')
        lines.extend(api_lines)
        lines.append('')

    # ── Internal dependency graph ─────────────
    graph_lines = _build_dep_graph(file_records, folder)
    if graph_lines:
        lines.append('## Internal Dependencies')
        lines.append('')
        lines.append('```')
        lines.extend(graph_lines)
        lines.append('```')
        lines.append('')

    # ── Health summary ────────────────────────
    total = len(file_records)
    ok = sum(1 for r in file_records if r['lines'] <= MAX_COMPLIANT)
    over = total - ok
    total_lines = sum(r['lines'] for r in file_records)
    total_tokens = sum(r['pigeon'].get('tokens', 0) for r in file_records)
    lines.append('## Health')
    lines.append(f'- **Files:** {total} | **Compliant:** {ok}/{total} ({ok/max(total,1)*100:.0f}%)')
    lines.append(f'- **Total lines:** {total_lines} | **Est. tokens:** ~{total_tokens} | **Target:** ≤{MAX_COMPLIANT} per file')
    if over:
        lines.append(f'- **Action needed:** {over} file(s) over limit')
    lines.append('')

    # ── Module signatures (LLM context) ───────
    sig_section = _build_signatures_section(file_records)
    if sig_section:
        lines.append('## Module Signatures')
        lines.append('')
        lines.append('Function and class signatures for LLM context (type hints included):')
        lines.append('')
        lines.extend(sig_section)
        lines.append('')

    # ── Constants & config values ────────────
    const_section = _build_constants_section(file_records)
    if const_section:
        lines.append('## Constants & Configuration')
        lines.append('')
        lines.extend(const_section)
        lines.append('')

    # ── Pigeon version table ─────────────────
    pigeon_section = _build_pigeon_table(file_records)
    if pigeon_section:
        lines.append('## Pigeon Metadata')
        lines.append('')
        lines.extend(pigeon_section)
        lines.append('')

    # ── Code markers (TODO/FIXME/HACK) ───────
    marker_section = _build_markers_section(file_records)
    if marker_section:
        lines.append('## Code Markers')
        lines.append('')
        lines.extend(marker_section)
        lines.append('')

    return '\n'.join(lines)
