"""cut_executor — Layer 3: Execute DeepSeek cut plans into real files.

Takes JSON cut plans, slices source by AST, writes Pigeon-compliant files,
fixes imports, writes manifests. The refactoring engine.
"""
from pigeon_compiler.cut_executor.plan_parser_seq001_v003_d0314__parse_deepseek_json_from_raw_lc_desc_upgrade import parse_plan
from pigeon_compiler.cut_executor.source_slicer_seq002_v003_d0314__extract_functions_constants_from_source_lc_desc_upgrade import slice_source
from pigeon_compiler.cut_executor.file_writer_seq003_v003_d0314__write_new_pigeon_compliant_files_lc_desc_upgrade import write_cut_files
from pigeon_compiler.cut_executor.import_fixer_seq004_v003_d0314__update_imports_across_the_project_lc_desc_upgrade import fix_imports
from pigeon_compiler.cut_executor.manifest_writer_seq005_v003_d0314__generate_manifest_md_for_a_lc_desc_upgrade import write_manifest
from pigeon_compiler.cut_executor.plan_validator_seq006_v003_d0314__validate_cut_plan_before_execution_lc_desc_upgrade import validate_plan
