"""manifest_writer_seq005_v001.py — Generate MANIFEST.md for a split folder.

Reads the new files, counts lines, lists exports, writes manifest.
"""

# ── pigeon ────────────────────────────────────
# SEQ: 005 | VER: v004 | 69 lines | ~448 tokens
# DESC:   generate_manifest_md_for_a
# INTENT: verify_pigeon_plugin
# LAST:   2026-03-15 @ caac48c
# SESSIONS: 1
# ──────────────────────────────────────────────
from pathlib import Path
from datetime import datetime


def write_manifest(target_dir: Path, plan: dict,
                   results: list) -> Path:
    """Write MANIFEST.md for the newly-created folder."""
    name = target_dir.name.upper()
    ts = datetime.now().strftime("%Y-%m-%d")
    files_table = _build_files_table(results)
    exports = plan.get("init_exports", [])
    strategy = plan.get("strategy", "")
    source = plan.get("source_file", "?")

    content = f"""# {target_dir.name}/ MANIFEST.md
## Pigeon-Extracted from `{source}`

**Strategy**: {strategy}
**Date**: {ts}

---

## 📁 FILES

{files_table}

---

## 🔌 EXPORTS

{_export_list(exports)}

---

## 📦 PROMPT BOX — {name} TASKS
*Generated by Pigeon Compiler | {ts}*

- [ ] **{name}-001**: Verify all imports resolve correctly
- [ ] **{name}-002**: Run folder_auditor on this folder
- [ ] **{name}-003**: Add unit tests for extracted functions
"""
    out = target_dir / "MANIFEST.md"
    out.write_text(content, encoding='utf-8')
    return out


def _build_files_table(results: list) -> str:
    rows = ["| File | Lines | Status |", "|------|-------|--------|"]
    for r in results:
        rows.append(f"| `{r['file']}` | {r['lines']} | {r['status']} |")
    return "\n".join(rows)


def _export_list(exports: list) -> str:
    if not exports:
        return "(none)"
    return "\n".join(f"- `{e}()`" for e in exports)
