"""press_release_gen_constants_seq001_v001_seq001_v001.py — Pigeon-extracted by compiler."""

PRESS_RELEASE_TEMPLATE = """# MAIF INTELLIGENCE REPORT
## {entity_name} — Drift Flags · Prediction · Void Map

**Published:** {timestamp}
**Source:** MyAIFingerprint Drift Intelligence
**Risk Level:** {risk_level} | **Severity:** {severity}/10
**Models Analyzed:** 7 (GPT-4o, Gemini, Grok, Perplexity, Kimi, Qwen, GLM)
**Report ID:** {report_id}
{prior_report_ref}

---

## 🔥 HEADLINE

{headline}

---

## EXECUTIVE SUMMARY

{executive_summary}

---

# SECTION 1: DRIFT FLAGS — WHAT CHANGED THIS CYCLE

> What mutated? Which models reversed? Where did consensus break?

{drift_flags}

### CONTRADICTIONS DETECTED

{contradictions_section}

### NEWS CORRELATION

{news_section}

---

# SECTION 2: PREDICTION — WHAT'S COMING NEXT

> Forward trajectory based on drift velocity, void patterns, and prior prediction accuracy.

{prediction_section}

### PRIOR PREDICTION ACCURACY

{prior_accuracy}

---

# SECTION 3: VOID MAP — WHAT NOBODY CAN ANSWER

> Semantic gaps, information holes, and questions no AI model can resolve.

{void_map}

---

# APPENDIX: CONSENSUS PROFILE

> Current model-by-model snapshot — what all 7 AI models say RIGHT NOW.

{current_snapshot}

### AI MODEL CONSENSUS STATUS

{model_status}

---

### METHODOLOGY

This report was auto-generated by MyAIFingerprint's Drift Intelligence engine.
The system audits entities across 7 AI models simultaneously, detects persona
mutations between audit cycles, flags contradictions where new data reverses
prior consensus, and correlates changes with real-world news events.

**Section 1** leads with what CHANGED — mutations, reversals, and contradictions
detected in this audit cycle compared to the last.

**Section 2** projects forward — where is the narrative heading, what do drift
patterns predict, and how accurate were our prior predictions?

**Section 3** maps what's UNKNOWN — semantic voids where no AI model has data,
questions that remain unanswered, and information gaps across the network.

**Appendix** provides the full consensus profile for reference.

No editorial judgment was applied. All findings are algorithmic.

---

*Report ID: {report_id} | Entity: {entity_name} | Generated: {timestamp}*
*© 2026 MyAIFingerprint — myaifingerprint.com*
"""
