"""rename_engine — Atomic whole-codebase rename with import rewriting.

Renames files and folders to Pigeon Code convention (_seqNNN_vNNN.py)
and fixes every import across the entire project in one pass.
Includes self-healing manifests that track operator intent.
"""
from pigeon_compiler.rename_engine.scanner_seq001_v004_d0315__walk_the_project_tree_and_lc_verify_pigeon_plugin import scan_project
from pigeon_compiler.rename_engine.planner_seq002_v004_d0315__generate_rename_plan_for_non_lc_verify_pigeon_plugin import build_rename_plan
from pigeon_compiler.rename_engine.import_rewriter_seq003_v004_d0316__rewrite_all_imports_across_the_lc_import_rewriter_now import rewrite_all_imports
from pigeon_compiler.rename_engine.executor_seq004_v004_d0315__execute_file_renames_with_rollback_lc_verify_pigeon_plugin import execute_rename
from pigeon_compiler.rename_engine.validator_seq005_v004_d0315__post_rename_import_validation_lc_verify_pigeon_plugin import validate_imports
from pigeon_compiler.rename_engine.run_rename_seq006_v004_d0315__full_rename_pipeline_runner_lc_verify_pigeon_plugin import run_full_rename
from pigeon_compiler.rename_engine.manifest_builder_seq007_v003_d0314__generate_living_manifest_md_per_lc_desc_upgrade import build_all_manifests, sync_master_structure
from pigeon_compiler.rename_engine.compliance_seq008_v004_d0315__line_count_enforcer_split_recommender_lc_verify_pigeon_plugin import audit_compliance
from pigeon_compiler.rename_engine.heal_seq009_v004_d0315__self_healing_orchestrator_lc_verify_pigeon_plugin import heal
from pigeon_compiler.rename_engine.run_heal_seq010_v004_d0315__automated_self_healing_pipeline_lc_verify_pigeon_plugin import run_heal_pipeline
from pigeon_compiler.rename_engine.nametag_seq011_v003_d0314__encode_file_description_intent_into_lc_desc_upgrade import (
    extract_desc_slug, build_nametag, scan_drift,
)
from pigeon_compiler.rename_engine.registry_seq012_v003_d0314__local_name_registry_for_the_lc_desc_upgrade import (
    load_registry, save_registry, build_registry_from_scan,
    build_pigeon_filename, parse_pigeon_stem,
    bump_version, bump_all_versions,
)
