"""manifest_builder_seq007_v001.py — Generate living MANIFEST.md per folder.

Scans each folder's .py files, extracts the module docstring (first line),
counts lines, checks compliance, and writes a MANIFEST.md that IS the
prompt map for that folder. Each file entry is a replicating note:
  filename | lines | status | description | notes

The NOTES column is the living part — it starts empty and grows via
heal_seq009 which reads git diffs and appends context on every push.
Existing notes are PRESERVED across rebuilds (merge, don't overwrite).
"""
import ast
import re
from datetime import datetime, timezone
from pathlib import Path
from pigeon_compiler.pigeon_limits import PIGEON_MAX, PIGEON_RECOMMENDED, is_excluded

SKIP_DIRS = {'.venv', '__pycache__', 'node_modules', '.git',
             '_llm_tests_put_all_test_and_debug_scripts_here',
             '.next', '.pytest_cache', 'compiler_output', 'rollback_logs',
             'audit_backups', 'json_uploads', 'logs', '.vscode', 'cache'}

SKIP_FILES = {'__init__.py', 'conftest.py'}

MAX_COMPLIANT = PIGEON_MAX


def build_manifest(folder: Path, root: Path = None) -> str:
    """Generate MANIFEST.md content for a single folder.

    Preserves existing NOTES from current MANIFEST.md if present.
    Returns the full markdown string.
    """
    folder = Path(folder)
    root = Path(root) if root else folder.parent
    existing_notes = _parse_existing_notes(folder / 'MANIFEST.md')
    files = _scan_folder(folder)
    if not files:
        return ''
    folder_rel = str(folder.relative_to(root)).replace('\\', '/')
    purpose = _infer_folder_purpose(folder)
    now = datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')
    lines = []
    lines.append(f'# MANIFEST — {folder_rel}')
    lines.append('')
    if purpose:
        lines.append(f'> {purpose}')
        lines.append('')
    lines.append(f'*Auto-generated by pigeon_compiler manifest_builder | {now}*')
    lines.append('')
    lines.append('## Files')
    lines.append('')
    lines.append('| Seq | File | Lines | Status | Description | Notes |')
    lines.append('|-----|------|------:|--------|-------------|-------|')
    for i, (name, lc, desc) in enumerate(files, 1):
        status = _status_icon(lc)
        seq = _extract_seq(name) or f'{i:03d}'
        note = existing_notes.get(name, '')
        lines.append(f'| {seq} | {name} | {lc} | {status} | {desc} | {note} |')
    lines.append('')
    # Summary
    total = len(files)
    ok = sum(1 for _, lc, _ in files if lc <= MAX_COMPLIANT)
    over = total - ok
    total_lines = sum(lc for _, lc, _ in files)
    lines.append(f'## Health')
    lines.append(f'- **Files:** {total} | **Compliant:** {ok}/{total} ({ok/max(total,1)*100:.0f}%)')
    lines.append(f'- **Total lines:** {total_lines} | **Target:** ≤{MAX_COMPLIANT} per file')
    if over:
        lines.append(f'- **Action needed:** {over} file(s) over limit')
    lines.append('')
    return '\n'.join(lines)


def build_all_manifests(root: Path, dry_run: bool = False) -> list[dict]:
    """Build MANIFEST.md for every folder that has .py files.

    Returns list of {folder, files, wrote} dicts.
    """
    root = Path(root)
    results = []
    seen = set()
    for py in sorted(root.rglob('*.py')):
        if _should_skip(py, root):
            continue
        folder = py.parent
        if folder in seen:
            continue
        seen.add(folder)
        content = build_manifest(folder, root)
        if not content:
            continue
        files_in = content.count('\n|') - 1  # minus header
        result = {'folder': str(folder.relative_to(root)).replace('\\', '/'),
                  'files': max(files_in, 0)}
        if not dry_run:
            (folder / 'MANIFEST.md').write_text(content, encoding='utf-8')
            result['wrote'] = True
        else:
            result['wrote'] = False
        results.append(result)
    # Sync project structure into MASTER_MANIFEST.md
    if not dry_run:
        sync_master_structure(root, results)
    return results


def _scan_folder(folder: Path) -> list[tuple]:
    """Return [(filename, line_count, description)] for .py files."""
    results = []
    for py in sorted(folder.glob('*.py')):
        if py.name in SKIP_FILES:
            continue
        try:
            text = py.read_text(encoding='utf-8', errors='ignore')
        except Exception:
            continue
        lc = len(text.splitlines())
        desc = _extract_docstring_first_line(text, py.name)
        results.append((py.name, lc, desc))
    return results


def _extract_docstring_first_line(text: str, filename: str) -> str:
    """Extract the first line of the module docstring."""
    try:
        tree = ast.parse(text)
        ds = ast.get_docstring(tree)
        if ds:
            first = ds.strip().split('\n')[0].strip()
            # If docstring starts with "filename.py — description",
            # extract just the description (the intent)
            if ' — ' in first:
                first = first.split(' — ', 1)[1].strip()
            elif ' - ' in first:
                parts = first.split(' - ', 1)
                if len(parts[0].split()) <= 4:
                    first = parts[1].strip()
            if len(first) > 80:
                first = first[:77] + '...'
            return first
    except SyntaxError:
        pass
    # Fallback: infer from filename
    stem = Path(filename).stem
    clean = re.sub(r'_seq\d+_v\d+', '', stem).replace('_', ' ').strip()
    return clean.capitalize() if clean else filename


def _extract_seq(filename: str) -> str:
    """Extract seq number from pigeon filename."""
    m = re.search(r'_seq(\d+)', filename)
    return m.group(1) if m else ''


def _status_icon(line_count: int) -> str:
    if line_count <= MAX_COMPLIANT:
        return '✅'
    elif line_count <= 300:
        return '⚠️ OVER'
    elif line_count <= 500:
        return '🟠 WARN'
    else:
        return '🔴 CRIT'


def _infer_folder_purpose(folder: Path) -> str:
    """Try to get folder purpose from __init__.py docstring or folder name."""
    init = folder / '__init__.py'
    if init.exists():
        try:
            text = init.read_text(encoding='utf-8', errors='ignore')
            tree = ast.parse(text)
            ds = ast.get_docstring(tree)
            if ds:
                return ds.strip().split('\n')[0].strip()
        except Exception:
            pass
    # Fallback: humanize folder name
    name = folder.name.replace('_', ' ').strip()
    return name.capitalize() if name else ''


def _parse_existing_notes(manifest_path: Path) -> dict:
    """Parse existing MANIFEST.md to preserve Notes column values.

    Returns {filename: notes_text} for any file that has notes.
    """
    notes = {}
    if not manifest_path.exists():
        return notes
    try:
        text = manifest_path.read_text(encoding='utf-8', errors='ignore')
    except Exception:
        return notes
    for line in text.splitlines():
        if not line.startswith('|'):
            continue
        cols = [c.strip() for c in line.split('|')]
        if len(cols) < 8:  # |seq|file|lines|status|desc|notes|
            continue
        fname = cols[2]
        if fname.endswith('.py') and cols[6]:
            notes[fname] = cols[6]
    return notes


def _should_skip(py: Path, root: Path) -> bool:
    parts = py.relative_to(root).parts
    for p in parts:
        if p in SKIP_DIRS or p.startswith('.venv') or p.startswith('_llm_tests'):
            return True
    return False


def sync_master_structure(root: Path, results: list[dict] = None):
    """Rebuild the PROJECT STRUCTURE section in MASTER_MANIFEST.md.

    Scans the actual filesystem and generates a current folder tree
    with file counts and compliance stats per folder.
    """
    master = root / 'documentation' / 'manifests' / 'MASTER_MANIFEST.md'
    if not master.exists():
        return
    content = master.read_text(encoding='utf-8')

    # Build the new structure block
    tree = _build_structure_tree(root)
    now = datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')
    new_section = (
        '## PROJECT STRUCTURE\n'
        f'*Auto-synced by manifest_builder | {now}*\n\n'
        '```\n'
        f'{tree}'
        '```'
    )

    # Replace the existing PROJECT STRUCTURE section
    start_marker = '## PROJECT STRUCTURE'
    start_idx = content.find(start_marker)
    if start_idx == -1:
        return

    # Find end: next ## heading or end of file
    rest = content[start_idx + len(start_marker):]
    end_match = re.search(r'\n## [A-Z]', rest)
    if end_match:
        end_idx = start_idx + len(start_marker) + end_match.start() + 1
    else:
        end_idx = len(content)

    content = content[:start_idx] + new_section + '\n\n' + content[end_idx:]
    master.write_text(content, encoding='utf-8')


def _build_structure_tree(root: Path) -> str:
    """Generate a text tree of the project folder structure with stats."""
    lines = ['LinkRouter.AI/\n']

    # Root files
    root_files = sorted(f for f in root.iterdir()
                        if f.is_file() and f.suffix in ('.py', '.md', '.txt', '.json', '.toml'))
    for f in root_files:
        if f.name.startswith('.'):
            continue
        lines.append(f'+-- {f.name}\n')

    lines.append('|\n')

    # Folders (1 level deep with file counts)
    folders = sorted(d for d in root.iterdir()
                     if d.is_dir() and d.name not in SKIP_DIRS
                     and not d.name.startswith('.'))
    for folder in folders:
        py_files = list(folder.rglob('*.py'))
        py_files = [p for p in py_files if '__pycache__' not in str(p)]
        if not py_files and not (folder / '__init__.py').exists():
            # Non-Python folder (static, templates, etc.)
            all_files = list(folder.rglob('*'))
            all_files = [f for f in all_files if f.is_file()]
            if all_files:
                lines.append(f'+-- /{folder.name:<35s} ({len(all_files)} files)\n')
            continue

        # Count compliance
        ok = warn = over = 0
        for py in py_files:
            if py.name == '__init__.py':
                continue
            try:
                lc = len(py.read_text(encoding='utf-8', errors='ignore').splitlines())
            except Exception:
                continue
            if lc <= PIGEON_RECOMMENDED:
                ok += 1
            elif lc <= MAX_COMPLIANT:
                warn += 1
            else:
                over += 1
        total = ok + warn + over
        if total == 0:
            lines.append(f'+-- /{folder.name:<35s} (package)\n')
            continue

        # Subfolder count
        subdirs = [d for d in folder.iterdir() if d.is_dir()
                   and d.name not in SKIP_DIRS and not d.name.startswith('__')]
        sub_str = f', {len(subdirs)} sub' if subdirs else ''
        pct = 100 * (ok + warn) / total if total else 0
        lines.append(
            f'+-- /{folder.name:<35s} '
            f'{total} files{sub_str} | '
            f'{pct:.0f}% compliant\n'
        )

        # Show subfolders (1 level)
        for sub in sorted(subdirs):
            sub_py = [p for p in sub.rglob('*.py')
                      if '__pycache__' not in str(p) and p.name != '__init__.py']
            if sub_py:
                lines.append(f'|   +-- /{sub.name:<31s} ({len(sub_py)} files)\n')

        lines.append('|\n')

    return ''.join(lines)
