"""manifest_builder — Generate self-documenting MANIFEST.md per folder.

Each MANIFEST.md is a complete reference for its folder:
  - Format legend so the manifest explains itself
  - File table with seq, lines, status, exports, dependencies, description
  - Folder API section showing the public contract from __init__.py
  - Internal dependency graph between files in the folder
  - Health summary with compliance stats

The NOTES column is the living part — it starts empty and grows via
heal_seq009 which reads git diffs and appends context on every push.
Existing notes are PRESERVED across rebuilds (merge, don't overwrite).
"""

import ast
import json
import re
from datetime import datetime, timezone
from pathlib import Path
from pigeon_compiler.pigeon_limits import PIGEON_MAX, PIGEON_RECOMMENDED, is_excluded

SKIP_DIRS = {'.venv', '__pycache__', 'node_modules', '.git',
             '_llm_tests_put_all_test_and_debug_scripts_here',
             '.next', '.pytest_cache', 'compiler_output', 'rollback_logs',
             'audit_backups', 'json_uploads', 'logs', '.vscode', 'cache'}

SKIP_FILES = {'__init__.py', 'conftest.py'}

MAX_COMPLIANT = PIGEON_MAX

_LEGEND = (
    '## How to read this manifest\n'
    '\n'
    'This file is **auto-generated** by `manifest_builder` and describes every\n'
    'Python module in this folder. It is the single source of truth for:\n'
    '- What each file does (Description)\n'
    '- What each file exports (Exports) and depends on (Deps)\n'
    '- Whether the file meets the Pigeon size budget (Status)\n'
    '- Living operator notes that persist across rebuilds (Notes)\n'
    '\n'
    '**Status icons:** '
    '✅ ≤{max} lines | '
    '⚠️ OVER {max}–300 | '
    '🟠 WARN 300–500 | '
    '🔴 CRIT >500\n'
    '\n'
    '**Columns:** '
    'Seq = load order · Lines = source line count · '
    'Exports = public classes/functions · Deps = intra-project imports\n'
)


def build_manifest(folder: Path, root: Path = None) -> str:
    """Generate self-documenting MANIFEST.md content for a single folder.

    Each manifest includes a format legend, a file table with exports and
    dependencies, the folder's public API, an internal dependency graph,
    and a health summary.  Existing NOTES are preserved across rebuilds.
    """
    folder = Path(folder)
    root = Path(root) if root else folder.parent
    existing_notes = _parse_existing_notes(folder / 'MANIFEST.md')
    file_records = _scan_folder_rich(folder)
    if not file_records:
        return ''
    folder_rel = str(folder.relative_to(root)).replace('\\', '/')
    purpose = _infer_folder_purpose(folder)
    now = datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')
    lines = []

    # ── Header ────────────────────────────────
    lines.append(f'# MANIFEST — {folder_rel}')
    lines.append('')
    if purpose:
        lines.append(f'> {purpose}')
        lines.append('')
    lines.append(f'*Auto-generated by pigeon_compiler manifest_builder | {now}*')
    lines.append('')

    # ── Self-documenting legend ───────────────
    lines.append(_LEGEND.format(max=MAX_COMPLIANT))
    lines.append('')

    # ── File table ────────────────────────────
    lines.append('## Files')
    lines.append('')
    lines.append('| Seq | File | Lines | Status | Exports | Deps | Description | Notes |')
    lines.append('|-----|------|------:|--------|---------|------|-------------|-------|')
    for rec in file_records:
        status = _status_icon(rec['lines'])
        seq = rec['seq']
        note = existing_notes.get(rec['name'], '')
        exports_str = ', '.join(rec['exports'][:5])
        if len(rec['exports']) > 5:
            exports_str += f' +{len(rec["exports"]) - 5}'
        deps_str = ', '.join(rec['deps'][:4])
        if len(rec['deps']) > 4:
            deps_str += f' +{len(rec["deps"]) - 4}'
        lines.append(
            f'| {seq} | {rec["name"]} | {rec["lines"]} | {status} '
            f'| {exports_str} | {deps_str} | {rec["desc"]} | {note} |'
        )
    lines.append('')

    # ── Folder API (from __init__.py) ─────────
    api_lines = _build_folder_api(folder)
    if api_lines:
        lines.append('## Folder API')
        lines.append('')
        lines.append('Public symbols re-exported by `__init__.py`:')
        lines.append('')
        lines.extend(api_lines)
        lines.append('')

    # ── Internal dependency graph ─────────────
    graph_lines = _build_dep_graph(file_records, folder)
    if graph_lines:
        lines.append('## Internal Dependencies')
        lines.append('')
        lines.append('```')
        lines.extend(graph_lines)
        lines.append('```')
        lines.append('')

    # ── Health summary ────────────────────────
    total = len(file_records)
    ok = sum(1 for r in file_records if r['lines'] <= MAX_COMPLIANT)
    over = total - ok
    total_lines = sum(r['lines'] for r in file_records)
    total_tokens = sum(r['pigeon'].get('tokens', 0) for r in file_records)
    lines.append('## Health')
    lines.append(f'- **Files:** {total} | **Compliant:** {ok}/{total} ({ok/max(total,1)*100:.0f}%)')
    lines.append(f'- **Total lines:** {total_lines} | **Est. tokens:** ~{total_tokens} | **Target:** ≤{MAX_COMPLIANT} per file')
    if over:
        lines.append(f'- **Action needed:** {over} file(s) over limit')
    lines.append('')

    # ── Module signatures (LLM context) ───────
    sig_section = _build_signatures_section(file_records)
    if sig_section:
        lines.append('## Module Signatures')
        lines.append('')
        lines.append('Function and class signatures for LLM context (type hints included):')
        lines.append('')
        lines.extend(sig_section)
        lines.append('')

    # ── Constants & config values ────────────
    const_section = _build_constants_section(file_records)
    if const_section:
        lines.append('## Constants & Configuration')
        lines.append('')
        lines.extend(const_section)
        lines.append('')

    # ── Pigeon version table ─────────────────
    pigeon_section = _build_pigeon_table(file_records)
    if pigeon_section:
        lines.append('## Pigeon Metadata')
        lines.append('')
        lines.extend(pigeon_section)
        lines.append('')

    # ── Code markers (TODO/FIXME/HACK) ───────
    marker_section = _build_markers_section(file_records)
    if marker_section:
        lines.append('## Code Markers')
        lines.append('')
        lines.extend(marker_section)
        lines.append('')

    return '\n'.join(lines)


def build_all_manifests(root: Path, dry_run: bool = False) -> list[dict]:
    """Build MANIFEST.md for every folder that has .py files.

    Returns list of {folder, files, wrote} dicts.
    """
    root = Path(root)
    results = []
    seen = set()
    for py in sorted(root.rglob('*.py')):
        if _should_skip(py, root):
            continue
        folder = py.parent
        if folder in seen:
            continue
        seen.add(folder)
        content = build_manifest(folder, root)
        if not content:
            continue
        files_in = content.count('\n|') - 1  # minus header
        result = {'folder': str(folder.relative_to(root)).replace('\\', '/'),
                  'files': max(files_in, 0)}
        if not dry_run:
            (folder / 'MANIFEST.md').write_text(content, encoding='utf-8')
            result['wrote'] = True
        else:
            result['wrote'] = False
        results.append(result)
    # Sync project structure into MASTER_MANIFEST.md
    if not dry_run:
        sync_master_structure(root, results)
    return results


def _scan_folder_rich(folder: Path) -> list[dict]:
    """Return list of file records with exports, deps, signatures, and pigeon metadata."""
    results = []
    for py in sorted(folder.glob('*.py')):
        if py.name in SKIP_FILES:
            continue
        try:
            text = py.read_text(encoding='utf-8', errors='ignore')
        except Exception:
            continue
        lc = len(text.splitlines())
        desc = _extract_docstring_first_line(text, py.name)
        exports = _extract_exports(text)
        deps = _extract_deps(text, folder.name)
        seq = _extract_seq(py.name) or f'{len(results)+1:03d}'
        pigeon = _parse_pigeon_header(text)
        signatures = _extract_signatures(text)
        classes = _extract_classes(text)
        constants = _extract_constants(text)
        markers = _extract_code_markers(text)
        results.append({
            'name': py.name,
            'lines': lc,
            'desc': desc,
            'exports': exports,
            'deps': deps,
            'seq': seq,
            'pigeon': pigeon,
            'signatures': signatures,
            'classes': classes,
            'constants': constants,
            'markers': markers,
        })
    return results


def _extract_docstring_first_line(text: str, filename: str) -> str:
    """Extract the first line of the module docstring."""
    try:
        tree = ast.parse(text)
        ds = ast.get_docstring(tree)
        if ds:
            first = ds.strip().split('\n')[0].strip()
            # If docstring starts with "filename.py — description",
            # extract just the description (the intent)
            if ' — ' in first:
                first = first.split(' — ', 1)[1].strip()
            elif ' - ' in first:
                parts = first.split(' - ', 1)
                if len(parts[0].split()) <= 4:
                    first = parts[1].strip()
            if len(first) > 80:
                first = first[:77] + '...'
            return first
    except SyntaxError:
        pass
    # Fallback: infer from filename
    stem = Path(filename).stem
    clean = re.sub(r'_seq\d+_v\d+', '', stem).replace('_', ' ').strip()
    return clean.capitalize() if clean else filename


def _extract_seq(filename: str) -> str:
    """Extract seq number from pigeon filename."""
    m = re.search(r'_seq(\d+)', filename)
    return m.group(1) if m else ''


def _extract_exports(text: str) -> list[str]:
    """Extract public class/function/constant names from a module."""
    try:
        tree = ast.parse(text)
    except SyntaxError:
        return []
    names = []
    for node in ast.iter_child_nodes(tree):
        if isinstance(node, ast.ClassDef) and not node.name.startswith('_'):
            names.append(node.name)
        elif isinstance(node, ast.FunctionDef) and not node.name.startswith('_'):
            names.append(f'{node.name}()')
        elif isinstance(node, (ast.Assign, ast.AnnAssign)):
            targets = []
            if isinstance(node, ast.Assign):
                targets = node.targets
            elif node.target:
                targets = [node.target]
            for t in targets:
                if isinstance(t, ast.Name) and t.id.isupper():
                    names.append(t.id)
    return names


def _extract_deps(text: str, folder_name: str) -> list[str]:
    """Extract intra-project import targets (module stems)."""
    deps = []
    try:
        tree = ast.parse(text)
    except SyntaxError:
        return deps
    for node in ast.walk(tree):
        if isinstance(node, ast.ImportFrom) and node.module:
            mod = node.module
            # Only track project-internal imports
            if any(mod.startswith(p) for p in ('src.', 'pigeon_compiler.', 'streaming_layer.')):
                # Extract the final module stem
                leaf = mod.rsplit('.', 1)[-1]
                # Strip pigeon suffixes for readability
                short = re.sub(r'_seq\d+.*', '', leaf)
                if short and short not in deps:
                    deps.append(short)
    return deps


def _parse_pigeon_header(text: str) -> dict:
    """Extract pigeon metadata from the # ── pigeon ── header block."""
    info = {}
    for line in text.splitlines()[:20]:
        line = line.strip().lstrip('#').strip()
        if line.startswith('SEQ:'):
            m = re.search(r'VER:\s*(v\d+)', line)
            if m:
                info['ver'] = m.group(1)
            m2 = re.search(r'~([\d,]+)\s*tokens', line)
            if m2:
                info['tokens'] = int(m2.group(1).replace(',', ''))
        elif line.startswith('LAST:'):
            info['last'] = line.split('LAST:', 1)[1].strip()
        elif line.startswith('SESSIONS:'):
            m = re.search(r'SESSIONS:\s*(\d+)', line)
            if m:
                info['sessions'] = int(m.group(1))
        elif line.startswith('INTENT:'):
            info['intent'] = line.split('INTENT:', 1)[1].strip()
    # Also check @pigeon comment for role
    for line in text.splitlines()[:5]:
        if line.startswith('# @pigeon:'):
            m = re.search(r'role=(\w+)', line)
            if m:
                info['role'] = m.group(1)
    return info


def _extract_signatures(text: str) -> list[str]:
    """Extract public function signatures with type hints."""
    try:
        tree = ast.parse(text)
    except SyntaxError:
        return []
    sigs = []
    for node in ast.iter_child_nodes(tree):
        if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
            if node.name.startswith('_'):
                continue
            sig = _format_signature(node)
            sigs.append(sig)
        elif isinstance(node, ast.ClassDef):
            for item in node.body:
                if isinstance(item, (ast.FunctionDef, ast.AsyncFunctionDef)):
                    if item.name.startswith('_') and item.name != '__init__':
                        continue
                    sig = _format_signature(item, class_name=node.name)
                    sigs.append(sig)
    return sigs


def _format_signature(node, class_name: str = None) -> str:
    """Format a function AST node into a readable signature string."""
    prefix = 'async ' if isinstance(node, ast.AsyncFunctionDef) else ''
    params = []
    args = node.args

    # Positional args
    defaults_offset = len(args.args) - len(args.defaults)
    for i, arg in enumerate(args.args):
        if arg.arg == 'self' or arg.arg == 'cls':
            continue
        p = arg.arg
        if arg.annotation:
            p += f': {ast.unparse(arg.annotation)}'
        if i >= defaults_offset:
            default = args.defaults[i - defaults_offset]
            try:
                p += f' = {ast.unparse(default)}'
            except Exception:
                p += ' = ...'
        params.append(p)

    # *args and **kwargs
    if args.vararg:
        p = f'*{args.vararg.arg}'
        if args.vararg.annotation:
            p += f': {ast.unparse(args.vararg.annotation)}'
        params.append(p)
    if args.kwarg:
        p = f'**{args.kwarg.arg}'
        if args.kwarg.annotation:
            p += f': {ast.unparse(args.kwarg.annotation)}'
        params.append(p)

    ret = ''
    if node.returns:
        ret = f' -> {ast.unparse(node.returns)}'

    name = node.name
    if class_name:
        name = f'{class_name}.{name}'
    return f'{prefix}def {name}({", ".join(params)}){ret}'


def _extract_classes(text: str) -> list[dict]:
    """Extract class definitions with methods and bases."""
    try:
        tree = ast.parse(text)
    except SyntaxError:
        return []
    classes = []
    for node in ast.iter_child_nodes(tree):
        if isinstance(node, ast.ClassDef) and not node.name.startswith('_'):
            bases = [ast.unparse(b) for b in node.bases] if node.bases else []
            decorators = []
            for d in node.decorator_list:
                try:
                    decorators.append(ast.unparse(d))
                except Exception:
                    pass
            methods = [m.name for m in node.body
                       if isinstance(m, (ast.FunctionDef, ast.AsyncFunctionDef))
                       and not m.name.startswith('_')]
            classes.append({
                'name': node.name,
                'bases': bases,
                'decorators': decorators,
                'methods': methods,
                'lines': (node.end_lineno or node.lineno) - node.lineno + 1,
            })
    return classes


def _extract_constants(text: str) -> list[dict]:
    """Extract module-level public constants with their values."""
    try:
        tree = ast.parse(text)
    except SyntaxError:
        return []
    consts = []
    for node in ast.iter_child_nodes(tree):
        if isinstance(node, ast.Assign):
            for t in node.targets:
                if isinstance(t, ast.Name) and t.id.isupper():
                    try:
                        val_str = ast.unparse(node.value)
                        if len(val_str) > 80:
                            val_str = val_str[:77] + '...'
                    except Exception:
                        val_str = '...'
                    consts.append({'name': t.id, 'value': val_str})
    return consts


_MARKER_RE = re.compile(r'#\s*(TODO|FIXME|HACK|XXX|WARN|NOTE)\b', re.IGNORECASE)


def _extract_code_markers(text: str) -> list[dict]:
    """Extract TODO/FIXME/HACK/NOTE markers from comments."""
    markers = []
    for i, line in enumerate(text.splitlines(), 1):
        m = _MARKER_RE.search(line)
        if m:
            tag = m.group(1).upper()
            rest = line[m.end():].strip().lstrip(':').strip()
            if len(rest) > 60:
                rest = rest[:57] + '...'
            markers.append({'tag': tag, 'line': i, 'text': rest})
    return markers


def _build_signatures_section(file_records: list[dict]) -> list[str]:
    """Build the Module Signatures section content."""
    lines = []
    for rec in file_records:
        if not rec['signatures'] and not rec['classes']:
            continue
        short = re.sub(r'_seq\d+.*', '', Path(rec['name']).stem)
        lines.append(f'**{short}**')
        lines.append('```python')
        for cls in rec['classes']:
            deco_parts = [f'@{d}' for d in cls['decorators']]
            bases_str = f'({", ".join(cls["bases"])})' if cls['bases'] else ''
            for dp in deco_parts:
                lines.append(dp)
            lines.append(f'class {cls["name"]}{bases_str}:  # {cls["lines"]} lines')
            if cls['methods']:
                lines.append(f'    # methods: {", ".join(cls["methods"])}')
        for sig in rec['signatures']:
            lines.append(sig)
        lines.append('```')
        lines.append('')
    return lines


def _build_constants_section(file_records: list[dict]) -> list[str]:
    """Build the Constants & Configuration section content."""
    all_consts = []
    for rec in file_records:
        for c in rec['constants']:
            short = re.sub(r'_seq\d+.*', '', Path(rec['name']).stem)
            all_consts.append((short, c['name'], c['value']))
    if not all_consts:
        return []
    lines = ['| Module | Constant | Value |',
             '|--------|----------|-------|']
    for mod, name, val in all_consts:
        val_escaped = val.replace('|', '\\|')
        lines.append(f'| {mod} | `{name}` | `{val_escaped}` |')
    return lines


def _build_pigeon_table(file_records: list[dict]) -> list[str]:
    """Build the Pigeon Metadata version/token/session table."""
    has_pigeon = any(r['pigeon'] for r in file_records)
    if not has_pigeon:
        return []
    lines = ['| File | Ver | Tokens | Sessions | Last Modified | Intent |',
             '|------|-----|-------:|---------:|---------------|--------|']
    for rec in file_records:
        p = rec['pigeon']
        if not p:
            continue
        short = re.sub(r'_seq\d+.*', '', Path(rec['name']).stem)
        ver = p.get('ver', '?')
        tokens = p.get('tokens', '?')
        sessions = p.get('sessions', '?')
        last = p.get('last', '?')
        intent = p.get('intent', '?')
        lines.append(f'| {short} | {ver} | {tokens} | {sessions} | {last} | {intent} |')
    return lines


def _build_markers_section(file_records: list[dict]) -> list[str]:
    """Build the Code Markers section for TODO/FIXME/HACK."""
    all_markers = []
    for rec in file_records:
        for m in rec['markers']:
            short = re.sub(r'_seq\d+.*', '', Path(rec['name']).stem)
            all_markers.append((short, m['tag'], m['line'], m['text']))
    if not all_markers:
        return ['*No TODO/FIXME/HACK markers found — codebase is clean.*']
    lines = ['| Module | Tag | Line | Note |',
             '|--------|-----|-----:|------|']
    for mod, tag, ln, txt in all_markers:
        lines.append(f'| {mod} | {tag} | {ln} | {txt} |')
    return lines


def _build_folder_api(folder: Path) -> list[str]:
    """Parse __init__.py to list the folder's public re-exports."""
    init = folder / '__init__.py'
    if not init.exists():
        return []
    try:
        text = init.read_text(encoding='utf-8', errors='ignore')
        tree = ast.parse(text)
    except Exception:
        return []
    lines = []
    # Check for __all__
    for node in ast.iter_child_nodes(tree):
        if isinstance(node, ast.Assign):
            for t in node.targets:
                if isinstance(t, ast.Name) and t.id == '__all__':
                    if isinstance(node.value, (ast.List, ast.Tuple)):
                        for elt in node.value.elts:
                            if isinstance(elt, ast.Constant) and isinstance(elt.value, str):
                                lines.append(f'- `{elt.value}`')
                    if lines:
                        return lines
    # Fallback: collect ImportFrom names
    for node in ast.walk(tree):
        if isinstance(node, ast.ImportFrom) and node.names:
            for alias in node.names:
                name = alias.asname or alias.name
                if not name.startswith('_'):
                    lines.append(f'- `{name}`')
    return lines


def _build_dep_graph(file_records: list[dict], folder: Path) -> list[str]:
    """Build a simple ASCII dependency graph between files in the folder."""
    # Map short stems to file names for intra-folder links
    stem_map = {}
    for rec in file_records:
        short = re.sub(r'_seq\d+.*', '', Path(rec['name']).stem)
        stem_map[short] = rec['name']

    graph_lines = []
    for rec in file_records:
        short_name = re.sub(r'_seq\d+.*', '', Path(rec['name']).stem)
        targets = [d for d in rec['deps'] if d in stem_map and d != short_name]
        if targets:
            arrow_targets = ', '.join(targets)
            graph_lines.append(f'{short_name} --> {arrow_targets}')
    return graph_lines


def _status_icon(line_count: int) -> str:
    if line_count <= MAX_COMPLIANT:
        return '✅'
    elif line_count <= 300:
        return '⚠️ OVER'
    elif line_count <= 500:
        return '🟠 WARN'
    else:
        return '🔴 CRIT'


def _infer_folder_purpose(folder: Path) -> str:
    """Try to get folder purpose from __init__.py docstring or folder name."""
    init = folder / '__init__.py'
    if init.exists():
        try:
            text = init.read_text(encoding='utf-8', errors='ignore')
            tree = ast.parse(text)
            ds = ast.get_docstring(tree)
            if ds:
                return ds.strip().split('\n')[0].strip()
        except Exception:
            pass
    # Fallback: humanize folder name
    name = folder.name.replace('_', ' ').strip()
    return name.capitalize() if name else ''


def _parse_existing_notes(manifest_path: Path) -> dict:
    """Parse existing MANIFEST.md to preserve Notes column values.

    Returns {filename: notes_text} for any file that has notes.
    """
    notes = {}
    if not manifest_path.exists():
        return notes
    try:
        text = manifest_path.read_text(encoding='utf-8', errors='ignore')
    except Exception:
        return notes
    for line in text.splitlines():
        if not line.startswith('|'):
            continue
        cols = [c.strip() for c in line.split('|')]
        if len(cols) < 8:  # |seq|file|lines|status|desc|notes|
            continue
        fname = cols[2]
        if fname.endswith('.py') and cols[6]:
            notes[fname] = cols[6]
    return notes


def _should_skip(py: Path, root: Path) -> bool:
    parts = py.relative_to(root).parts
    for p in parts:
        if p in SKIP_DIRS or p.startswith('.venv') or p.startswith('_llm_tests'):
            return True
    return False


def sync_master_structure(root: Path, results: list[dict] = None):
    """Rebuild the PROJECT STRUCTURE section in MASTER_MANIFEST.md.

    Scans the actual filesystem and generates a current folder tree
    with file counts and compliance stats per folder.
    """
    master = root / 'MASTER_MANIFEST.md'
    if not master.exists():
        return
    content = master.read_text(encoding='utf-8')

    # Build the new structure block
    tree = _build_structure_tree(root)
    now = datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')
    new_section = (
        '## FOLDER TREE\n'
        f'*Auto-synced by manifest_builder | {now}*\n\n'
        '```\n'
        f'{tree}'
        '```'
    )

    # Replace the existing FOLDER TREE section
    start_marker = '## FOLDER TREE'
    start_idx = content.find(start_marker)
    if start_idx == -1:
        return

    # Find end: next ## heading or end of file
    rest = content[start_idx + len(start_marker):]
    end_match = re.search(r'\n## [A-Z]', rest)
    if end_match:
        end_idx = start_idx + len(start_marker) + end_match.start() + 1
    else:
        end_idx = len(content)

    content = content[:start_idx] + new_section + '\n\n' + content[end_idx:]

    # Inject or replace OPERATOR KEYSTROKE TRAIL section
    trail_section = _build_keystroke_trail(root, now)
    if trail_section:
        trail_marker = '## OPERATOR KEYSTROKE TRAIL'
        trail_idx = content.find(trail_marker)
        if trail_idx != -1:
            rest_t = content[trail_idx + len(trail_marker):]
            end_t = re.search(r'\n## [A-Z]', rest_t)
            if end_t:
                trail_end = trail_idx + len(trail_marker) + end_t.start() + 1
            else:
                trail_end = len(content)
            content = content[:trail_idx] + trail_section + '\n\n' + content[trail_end:]
        else:
            # Append before CHANGELOG if it exists, else at end
            changelog_idx = content.find('## CHANGELOG')
            if changelog_idx != -1:
                content = content[:changelog_idx] + trail_section + '\n\n' + content[changelog_idx:]
            else:
                content = content.rstrip() + '\n\n' + trail_section + '\n'

    master.write_text(content, encoding='utf-8')


def _build_structure_tree(root: Path) -> str:
    """Generate a text tree of the project folder structure with stats."""
    lines = ['LinkRouter.AI/\n']

    # Root files
    root_files = sorted(f for f in root.iterdir()
                        if f.is_file() and f.suffix in ('.py', '.md', '.txt', '.json', '.toml'))
    for f in root_files:
        if f.name.startswith('.'):
            continue
        lines.append(f'+-- {f.name}\n')

    lines.append('|\n')

    # Folders (1 level deep with file counts)
    folders = sorted(d for d in root.iterdir()
                     if d.is_dir() and d.name not in SKIP_DIRS
                     and not d.name.startswith('.'))
    for folder in folders:
        py_files = list(folder.rglob('*.py'))
        py_files = [p for p in py_files if '__pycache__' not in str(p)]
        if not py_files and not (folder / '__init__.py').exists():
            # Non-Python folder (static, templates, etc.)
            all_files = list(folder.rglob('*'))
            all_files = [f for f in all_files if f.is_file()]
            if all_files:
                lines.append(f'+-- /{folder.name:<35s} ({len(all_files)} files)\n')
            continue

        # Count compliance
        ok = warn = over = 0
        for py in py_files:
            if py.name == '__init__.py':
                continue
            try:
                lc = len(py.read_text(encoding='utf-8', errors='ignore').splitlines())
            except Exception:
                continue
            if lc <= PIGEON_RECOMMENDED:
                ok += 1
            elif lc <= MAX_COMPLIANT:
                warn += 1
            else:
                over += 1
        total = ok + warn + over
        if total == 0:
            lines.append(f'+-- /{folder.name:<35s} (package)\n')
            continue

        # Subfolder count
        subdirs = [d for d in folder.iterdir() if d.is_dir()
                   and d.name not in SKIP_DIRS and not d.name.startswith('__')]
        sub_str = f', {len(subdirs)} sub' if subdirs else ''
        pct = 100 * (ok + warn) / total if total else 0
        lines.append(
            f'+-- /{folder.name:<35s} '
            f'{total} files{sub_str} | '
            f'{pct:.0f}% compliant\n'
        )

        # Show subfolders (1 level)
        for sub in sorted(subdirs):
            sub_py = [p for p in sub.rglob('*.py')
                      if '__pycache__' not in str(p) and p.name != '__init__.py']
            if sub_py:
                lines.append(f'|   +-- /{sub.name:<31s} ({len(sub_py)} files)\n')

        lines.append('|\n')

    return ''.join(lines)


# ── Operator keystroke trail ──────────────────

LOG_DIRS = ('test_logs', 'demo_logs', 'stress_logs')
PAUSE_THRESHOLD_MS = 2000
BACKSPACE_BURST_MIN = 3
TRAIL_LIMIT = 50


def _build_keystroke_trail(root: Path, now: str) -> str:
    """Build the OPERATOR KEYSTROKE TRAIL section for MASTER_MANIFEST.md.

    Reads the most recent event JSONL files across all log directories,
    extracts the last 50 keystrokes, and annotates them with:
      ⏸  pause  — gap > 2 s between keystrokes
      ⌫  burst  — 3+ consecutive backspaces
      🗑 discard — message was abandoned / deleted
      ✓  submit — message was submitted

    Also loads matching summary files for per-message hesitation scores.
    """
    # Collect all event files sorted by modification time (most recent last)
    event_files = []
    for d in LOG_DIRS:
        log_dir = root / d
        if log_dir.is_dir():
            for f in log_dir.glob('events_*.jsonl'):
                event_files.append(f)
    if not event_files:
        return ''
    event_files.sort(key=lambda p: p.stat().st_mtime)

    # Load events from the most recent files until we have >= TRAIL_LIMIT
    all_events = []
    for ef in reversed(event_files):
        try:
            lines = ef.read_text(encoding='utf-8', errors='ignore').strip().splitlines()
            events = [json.loads(ln) for ln in lines if ln.strip()]
            all_events = events + all_events
        except Exception:
            continue
        if len(all_events) >= TRAIL_LIMIT:
            break
    if not all_events:
        return ''

    # Take last TRAIL_LIMIT events
    trail = all_events[-TRAIL_LIMIT:]

    # Load summary files for hesitation lookup
    hes_map = _load_hesitation_map(root)

    # Build annotated trail
    lines = []
    lines.append('## OPERATOR KEYSTROKE TRAIL')
    lines.append('')
    lines.append(f'*Last {len(trail)} keystrokes | auto-synced by manifest_builder | {now}*')
    lines.append('')
    lines.append('> **How to read**: Each row is one keystroke event from the operator.')
    lines.append('> Markers flag cognitive signals: ⏸ = long pause (>2s), ')
    lines.append('> ⌫ = backspace burst (3+), ✓ = submitted, 🗑 = discarded.')
    lines.append('> Hesitation scores come from session summaries (0.0 = confident, 1.0 = max hesitation).')
    lines.append('')
    lines.append('| # | Key | Event | Δms | Buffer | Markers |')
    lines.append('|---|-----|-------|----:|--------|---------|')

    # Pre-compute backspace bursts
    burst_indices = _find_backspace_bursts(trail)

    for i, ev in enumerate(trail):
        markers = []
        delta = ev.get('delta_ms', 0)
        etype = ev.get('event_type', '')
        key = ev.get('key', '')
        buf = ev.get('buffer', '')
        msg_id = ev.get('message_id', '')

        # Pause marker
        if delta > PAUSE_THRESHOLD_MS:
            markers.append(f'⏸ {delta/1000:.1f}s')

        # Backspace burst marker
        if i in burst_indices:
            markers.append('⌫ burst')

        # Submit / discard markers (on submit/discard event types)
        if etype == 'submit':
            hes = hes_map.get(msg_id)
            tag = '✓ submit'
            if hes is not None:
                tag += f' (hes={hes:.3f})'
            markers.append(tag)
        elif etype == 'discard':
            hes = hes_map.get(msg_id)
            tag = '🗑 discard'
            if hes is not None:
                tag += f' (hes={hes:.3f})'
            markers.append(tag)

        # Truncate buffer for readability
        buf_display = buf if len(buf) <= 30 else buf[:27] + '...'
        # Escape pipe characters in buffer
        buf_display = buf_display.replace('|', '\\|')
        marker_str = ' '.join(markers)
        seq = i + 1
        lines.append(f'| {seq} | `{key}` | {etype} | {delta} | `{buf_display}` | {marker_str} |')

    lines.append('')

    # Append hesitation summary for recent messages
    hes_summary = _build_hesitation_summary(root)
    if hes_summary:
        lines.append('### Recent message hesitation scores')
        lines.append('')
        lines.append('| Message | Submitted | Keys | Dels | Hesitation | State |')
        lines.append('|---------|-----------|-----:|-----:|-----------:|-------|')
        lines.extend(hes_summary)
        lines.append('')

    return '\n'.join(lines)


def _find_backspace_bursts(events: list[dict]) -> set[int]:
    """Return indices that are part of a backspace burst (3+ consecutive)."""
    burst_indices = set()
    run_start = None
    for i, ev in enumerate(events):
        if ev.get('event_type') in ('backspace', 'delete'):
            if run_start is None:
                run_start = i
        else:
            if run_start is not None and (i - run_start) >= BACKSPACE_BURST_MIN:
                for j in range(run_start, i):
                    burst_indices.add(j)
            run_start = None
    # Handle burst at end of trail
    if run_start is not None and (len(events) - run_start) >= BACKSPACE_BURST_MIN:
        for j in range(run_start, len(events)):
            burst_indices.add(j)
    return burst_indices


def _load_hesitation_map(root: Path) -> dict:
    """Load message_id → hesitation_score from all summary files."""
    hes = {}
    for d in LOG_DIRS:
        log_dir = root / d
        if not log_dir.is_dir():
            continue
        for sf in log_dir.glob('summary_*.json'):
            try:
                data = json.loads(sf.read_text(encoding='utf-8', errors='ignore'))
                for msg in data.get('messages', []):
                    mid = msg.get('message_id', '')
                    if mid:
                        hes[mid] = msg.get('hesitation_score', 0.0)
            except Exception:
                continue
    return hes


def _build_hesitation_summary(root: Path) -> list[str]:
    """Build recent-message hesitation table rows from newest summaries."""
    all_msgs = []
    for d in LOG_DIRS:
        log_dir = root / d
        if not log_dir.is_dir():
            continue
        for sf in sorted(log_dir.glob('summary_*.json'),
                         key=lambda p: p.stat().st_mtime, reverse=True):
            try:
                data = json.loads(sf.read_text(encoding='utf-8', errors='ignore'))
                for msg in data.get('messages', []):
                    all_msgs.append(msg)
            except Exception:
                continue
            if len(all_msgs) >= 12:
                break
        if len(all_msgs) >= 12:
            break

    rows = []
    for msg in all_msgs[-12:]:
        mid = msg.get('message_id', '?')[:10]
        submitted = '✓' if msg.get('submitted') else '🗑'
        keys = msg.get('total_keystrokes', 0)
        dels = msg.get('total_deletions', 0)
        hes = msg.get('hesitation_score', 0.0)
        # Classify cognitive state inline
        state = _classify_msg_state(msg)
        rows.append(f'| `{mid}` | {submitted} | {keys} | {dels} | {hes:.3f} | {state} |')
    return rows


def _classify_msg_state(msg: dict) -> str:
    """Lightweight cognitive state classification for summary display."""
    keys = max(msg.get('total_keystrokes', 0), 1)
    dels = msg.get('total_deletions', 0)
    hes = msg.get('hesitation_score', 0.0)
    del_ratio = dels / keys
    if msg.get('deleted'):
        return 'abandoned'
    if hes > 0.6:
        return 'frustrated'
    if hes > 0.4:
        return 'hesitant'
    if del_ratio > 0.20:
        return 'restructuring'
    if hes < 0.15 and del_ratio < 0.05:
        return 'flow'
    if hes < 0.25:
        return 'focused'
    return 'neutral'
