"""self_fix_seq013/ — Pigeon-compliant module."""
from .self_fix_seq013_auto_apply_import_fixes_decomposed_seq011_v002_d0329__auto_extracted_by_pigeon_compiler_lc_organism_health_system import _HC_BARE_IMPORT, _HC_FROM_IMPORT, auto_apply_import_fixes
from .self_fix_seq013_auto_compile_oversized_decomposed_seq009_v002_d0329__auto_extracted_by_pigeon_compiler_lc_organism_health_system import auto_compile_oversized
from .self_fix_seq013_run_self_fix_decomposed_seq008_v002_d0329__auto_extracted_by_pigeon_compiler_lc_organism_health_system import run_self_fix
from .self_fix_seq013_write_report_decomposed_seq007_v002_d0329__auto_extracted_by_pigeon_compiler_lc_organism_health_system import write_self_fix_report
